version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  revamp-dev: # name of the first service
    build: 
      context: .
      args:
        - APP_DIR=/FE-REVAMP
      dockerfile: Dockerfile
    environment:
      - APP_DIR=/FE-REVAMP
    container_name: fe-revamp
    image: fe-revamp-angular
    volumes:
      - .:/FE-REVAMP/:rw
    ports:
      - "4100:4100" # specify port forwarding
    restart: always
